default: &default
  adapter: mysql2
  encoding: utf8
  database: smj
  pool: 5
  username: root
  password: smjcau2017!
  socket: /tmp/mysql.sock

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default